import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "../layout/Footer/footer"
import Header from "../layout/Header/header"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default function RootLayout({
  children,
}:Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header /> 
      {children}
      <Footer/>
    </body>
    </html>
  )
}
